#' Download R package source tarballs
#'
#' Downloads R package source tarballs from a CRAN mirror. Skips packages that
#' have already been downloaded. Returns a data frame summarizing the result of
#' each download attempt. Optionally checks MD5 hashes and adds SHA-256 hashes.
#' This function is intended for evaluating pkgaudit rules against all packages
#' currently hosted by CRAN.
#'
#' @param pkgs Data frame with columns Package (character), Version
#'   (character), and (optionally) MD5sum (character) identifying the packages
#'   to be downloaded. These are available via `available.packages()`.
#' @param dir Path to a destination directory. Created if it does not exist.
#' @param check_md5 Logical indicating if MD5 hash of downloaded tarball should
#'   be generated by `tools::md5sum()` and compared to MD5 hash in `pkgs$MD5sum`.
#'   If TRUE, adds md5_cran, md5_local, and md5_matches columns to the returned
#'   data frame. Defaults to TRUE. MD5 is what CRAN publishes; `add_sha256`
#'   records a stronger local hash alongside it.
#' @param add_sha256 Logical indicating if SHA-256 hash of downloaded tarball
#'   should be generated by `digest::digest(algo="sha256")`. If TRUE, adds
#'   sha256_local to the returned data frame. Defaults to TRUE.
#' @param mirror Base URL of a CRAN mirror. Defaults to RStudio/Posit global
#'   mirror.
#' @param pause Number of seconds to pause between downloads. Set to 0 for no
#'   pause. Be considerate of mirror bandwidth. Defaults to 0.5.
#'
#' @return A data frame with one row per package. The base columns are always
#'   present; the md5_* columns are added only when `check_md5 = TRUE` and
#'   sha256_local only when `add_sha256 = TRUE`:
#'   package      Package name
#'   version      Package version
#'   filename     Tarball filename
#'   path         Full path to the downloaded file on success, NA on failure
#'   status       One of "downloaded", "skipped" (already exists), or "failed"
#'   message      Empty string on success, error message on failure
#'   md5_cran     MD5 hash provided by `pkgs$MD5sum`
#'   md5_local    MD5 hash for downloaded tarball
#'   md5_matches  Logical indicating if md5_cran and md5_local match (NA if
#'                either hash is unavailable)
#'   sha256_local SHA-256 hash for downloaded tarball
#'
#' @examples
#' \dontrun{
#' db   <- available.packages(fields = "MD5sum")
#' pkgs <- as.data.frame(db[, c("Package", "Version", "MD5sum")],
#'                       stringsAsFactors = FALSE)
#' pkgs <- pkgs[sample(nrow(pkgs), 5L), ]
#' downloads <- download_cran(
#'   pkgs       = pkgs,
#'   dir        = tempfile("cran"),
#'   check_md5  = TRUE,
#'   add_sha256 = TRUE
#' )
#' }
download_cran <- function(
  pkgs,
  dir,
  check_md5  = TRUE,
  add_sha256 = TRUE,
  mirror     = "https://cloud.r-project.org",
  pause      = 0.5
) {
  # --- Input Validation -------------------------------------------------------
  stopifnot(is.data.frame(pkgs))
  stopifnot(all(c("Package", "Version") %in% colnames(pkgs)))
  stopifnot(is.character(dir), length(dir) == 1L)
  stopifnot(is.logical(check_md5),  length(check_md5)  == 1L, !is.na(check_md5))
  stopifnot(is.logical(add_sha256), length(add_sha256) == 1L, !is.na(add_sha256))
  if (check_md5 && !("MD5sum" %in% colnames(pkgs))) {
    stop("check_md5 = TRUE requires an 'MD5sum' column in pkgs.")
  }
  stopifnot(is.character(mirror),  length(mirror)   == 1L)
  stopifnot(is.numeric(pause), length(pause) == 1L, pause >= 0)

  if (!dir.exists(dir)) {
    dir.create(dir, recursive = TRUE)
    message("Created destination directory: ", dir)
  }

  # --- Downloading ------------------------------------------------------------
  # Normalizes mirror URL: removes trailing slash
  mirror <- sub("/+$", "", mirror)

  n <- nrow(pkgs)
  message("Downloading ", n, " package(s) to ", dir, " ...")

  results <- vector("list", n)

  for (i in seq_len(n)) {
    pkg     <- pkgs$Package[[i]]
    version <- pkgs$Version[[i]]
    fname   <- paste0(pkg, "_", version, ".tar.gz")
    url     <- paste0(mirror, "/src/contrib/", fname)
    path    <- file.path(dir, fname)

    result <- list(
      package  = pkg,
      version  = version,
      filename = fname,
      path     = NA_character_,
      status   = NA_character_,
      message  = ""
    )

    # Skip if already downloaded
    if (file.exists(path)) {
      result$path   <- path
      result$status <- "skipped"
      message("  [", i, "/", n, "] Skipped (exists): ", fname)
      results[[i]]  <- result
      next
    }

    # Attempt download. suppressWarnings() muffles download.file()'s own warning
    # (e.g. "URL ...: status was ...") since the error it also raises is already
    # captured below. A non-erroring call that leaves no/empty file (e.g. a
    # truncated write) is routed to the same failure handler via stop().
    tryCatch({
      status <- suppressWarnings(download.file(
        url      = url,
        destfile = path,
        mode     = "wb",
        quiet    = TRUE
      ))
      if (!identical(status, 0L) || !file.exists(path) || file.size(path) == 0) {
        stop("download did not produce a non-empty file (status ", status, ")")
      }
      result$path   <- path
      result$status <- "downloaded"
      message("  [", i, "/", n, "] Downloaded: ", fname)
    }, error = function(e) {
      # download.file() can leave a partial/empty file on failure. Remove it so
      # a later run does not treat the truncated file as already downloaded.
      if (file.exists(path)) unlink(path)
      result$status  <<- "failed"
      result$message <<- conditionMessage(e)
      message("  [", i, "/", n, "] Failed: ", fname, " -- ",
        conditionMessage(e))
    })

    results[[i]] <- result

    if (pause > 0 && i < n) Sys.sleep(pause)
  }

  out <- if (length(results) == 0L) {
    data.frame(
      package  = character(0L), version = character(0L),
      filename = character(0L), path    = character(0L),
      status   = character(0L), message = character(0L),
      stringsAsFactors = FALSE
    )
  } else {
    do.call(rbind, lapply(results, as.data.frame, stringsAsFactors = FALSE))
  }
  rownames(out) <- NULL

  # --- Post-download Hashing --------------------------------------------------
  # Hash each tarball on disk with a single read, computing only the requested
  # digests. Covers freshly downloaded and previously present ("skipped") files.
  has_file <- !is.na(out$path) & file.exists(out$path)
  hashes   <- .hash_local(out$path, has_file, md5 = check_md5,
    sha256 = add_sha256)

  if (check_md5)  out <- .add_md5_columns(out, pkgs, hashes$md5_local)
  if (add_sha256) out$sha256_local <- hashes$sha256_local

  # --- Summary ----------------------------------------------------------------
  n_downloaded <- sum(out$status == "downloaded")
  n_skipped    <- sum(out$status == "skipped")
  n_failed     <- sum(out$status == "failed")

  message(
    "Done. ",
    n_downloaded, " downloaded, ",
    n_skipped,    " skipped, ",
    n_failed,     " failed."
  )

  if (check_md5) {
    n_match    <- sum(out$md5_matches, na.rm = TRUE)
    n_mismatch <- sum(!out$md5_matches, na.rm = TRUE)
    n_unver    <- sum(is.na(out$md5_matches))
    message(sprintf(
      "MD5: %d matched, %d mismatched, %d unverifiable (of %d).",
      n_match, n_mismatch, n_unver, nrow(out)
    ))
  }

  invisible(out)
}


# --- Helpers ------------------------------------------------------------------

# Read each present tarball once and compute the requested content hashes from
# its bytes. Hashing bytes is identical to hashing the file (tools::md5sum() /
# digest(file = TRUE)) but avoids a second read when both digests are wanted.
# `has_file` marks rows whose tarball is present on disk; other rows stay NA, as
# do rows for a digest that was not requested or a file that could not be read.
.hash_local <- function(paths, has_file, md5, sha256) {
  n            <- length(paths)
  md5_local    <- rep(NA_character_, n)
  sha256_local <- rep(NA_character_, n)

  if (md5 || sha256) {
    for (i in which(has_file)) {
      bytes <- tryCatch(
        readBin(paths[i], what = "raw", n = file.size(paths[i])),
        error = function(e) NULL
      )
      if (is.null(bytes)) next
      if (md5)    md5_local[i]    <- digest::digest(bytes, algo = "md5",
        serialize = FALSE)
      if (sha256) sha256_local[i] <- digest::digest(bytes, algo = "sha256",
        serialize = FALSE)
    }
  }

  list(md5_local = md5_local, sha256_local = sha256_local)
}

# Add MD5 columns to a download result frame: md5_cran (CRAN reference from
# pkgs$MD5sum, aligned row-for-row with `out`), md5_local (precomputed by
# .hash_local()), and md5_matches (TRUE/FALSE, or NA "unverifiable" when either
# hash is unknown).
.add_md5_columns <- function(out, pkgs, md5_local) {
  md5_cran <- tolower(trimws(as.character(pkgs$MD5sum)))
  md5_cran[is.na(md5_cran) | !nzchar(md5_cran)] <- NA_character_

  out$md5_cran    <- md5_cran
  out$md5_local   <- md5_local
  out$md5_matches <- ifelse(
    !is.na(md5_cran) & !is.na(md5_local),
    md5_cran == md5_local,
    NA
  )
  out
}
