# .github/workflows/dependency-review.yaml
on:
  pull_request:

permissions:
  contents: read

name: dependency-review.yaml

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
