# .github/workflows/dependency-review.yaml
# This workflow targets GitHub Actions vulnerabilities. See osv-scanner.yaml for
# workflow targeting R vulnerabilities.

# Note: dependency-review-action only works for actions with semantic
# versioning. In general, this repo aims to use SHA pinning, but this action is
# included as belt and suspenders.
name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v4
