# .github/workflows/dependency-review.yaml
# This workflow targets GitHub Actions vulnerabilities. See osv-scanner.yaml for
# workflow targeting R vulnerabilities.

# Note: dependency-review-action only works for actions with semantic
# versioning. In general, this repo aims to use SHA pinning, but this action is
# included as belt and suspenders.
name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4
