# .github/workflows/R-CMD-check.yaml
# This workflow runs R CMD check, the standard check for R packages, across
# Windows, macOS, and Ubuntu, covering the current release of R, the previous
# release of R, and the development version of R.

# Note: R CMD check runs the full test suite. Any test failure produces an
# error, which will fail the workflow.
name: R CMD check

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
